language: node_js
node_js:
- 10.15.3
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: aJu4kNoxfXIgPkaezBrN/Mcf9njLxpw+EksKhM24Wm1Kviqr/7/RtXkw8zaRRQyuae78X5KlySWMmEEvgCistgW6eGN1+FDqnZkIY4pt0xC3q78RiobCd+3cyFxvtrIkpJW27PYrmXwOqMc3w6OdLsT3pShTwDGsotZ1zz+bvOQL6pb3NzoZy7wY5K+r16x66cd4+66W2WNjWUsxgWfFjRviEZQoWhKtZNXHqSblUPkpbZxcVgRLfu19KlJpmCwHVyuMlq90mQH8Hx8eRCjk79sV2nnE0IkhTqR1a5ng5kfDyUw0Xqy6ROH+98QFcU+PxsgGaI9MtvDQyUPXCc0x0EzzY+qlizYNGwb9KGF6oEMX2hNjsR0qyiS/1xOtkbpKIxKuux4qwGeaw42JG5KL8jYrjbpzqlpI3xBtoDMLFaid7sis2oMOB16JPVTd8XJXP8x31wdxE7WcakNow7LvW8lxjVC7TvUwGyvNN2FKlmTad0aMpuLJJYqtjCLMEi8ShOQmcMzZopQQjMIdXWuVpMHmQfJXRcb6NkVQTNfpvKe8Z49GU72GmvdsVYQMiXPrVjzP95OVs/EV+GH7E8T6qVrUMdGsh5HYsq13LzQ9G+WPGL0ZvysUoKZm8331rw9RPYizbHssussfhhG0QD9NTAoSzz5lRBoM4ejWkj3APGw=
