language: node_js
node_js:
- 10.15.3
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: A9haFU24xiGTm5Zl0CTmFRWGEZ40d+EopjDC6nC9rLrgMHoxNCqoGTYW/Ll4ZOSJLXEuf3HofBOpEwHKhSeDDxIypse5mT4PV2FJJLnmCTrU6iYf85Vg32OWNaKI96x6OzbK8Q9zRrylo+yilrOQb+vwGYYzghFq9obIZStHLxyQhSHvJuQh1lBZ3eJYo6/lPlwYNt8L9qNcXPSqrPzU35WIZgRDDCosoU6brhkxAqvOSWzMvvkhqugGinQVBiDe5ifnFrqGr4h/v40457NiO5VM2Q9yiV73VOnP4FK/KIPxei2nkCi85E0y58LCA2AzmRIUQf5d/cwlBLGD97yLHzZyev0Q7vJH5bzVZ0lboyP3DbAQwh8MktPTLBfez8oXI6dnpsU4MDEZwwDQwspgqw8B1tIgCe/wd9d4nEfvhzNvVzNeT6hrhyfkSTykmvqPYO010rfl3pkNuuYYa3QFzFRdWh5Wcuhp3ffXWwJecBIBCOEel8GpJwKmgPogddtY3eDex9zE6vngfE3t+z1X3GMDPWEdDSjnY15lKuBvQQ2O3HwFtdFh8vJbrsfMqJZfTjY6RWKMvHIt9BvmXnSvy2zQQC0GkXiW9M0jjUZxoedSPkAi2NU54z3p3/rjbBsh9wdjLisPpCvJYnnfUuo9YdYt7QihOcZrByRryCGGH4k=
